// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef fl_dmlconfig_h
#define fl_dmlconfig_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern void OnConfigClose(Fl_Double_Window*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Return_Button.H>
extern void OnConfigDone(Fl_Return_Button*, void*);
#include <FL/Fl_Check_Browser.H>
extern void OnConfigChanged(Fl_Check_Browser*, void*);
extern Fl_Check_Browser *pCFGList;
#endif
