// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef fl_mainwnd_h
#define fl_mainwnd_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Return_Button.H>
extern void OnConfigure(Fl_Return_Button*, void*);
#include <FL/Fl_Button.H>
extern void OnExit(Fl_Button*, void*);
#include <FL/Fl_Browser.H>
extern void OnSelect(Fl_Browser*, void*);
extern Fl_Browser *pDMLList;
extern void OnToggle(Fl_Button*, void*);
#include <FL/Fl_Input.H>
extern void OnSearch(Fl_Input*, void*);
extern Fl_Input *pDMLSearch;
#endif
