// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "fl_mainwnd.h"

static Fl_Double_Window *pMainWnd=(Fl_Double_Window *)0;

Fl_Browser *pDMLList=(Fl_Browser *)0;

Fl_Input *pDMLSearch=(Fl_Input *)0;

static Fl_Double_Window* MakeWindow() {
  { pMainWnd = new Fl_Double_Window(SCALE(640), SCALE(480), "T2FMDML Configuration");
    { Fl_Box* o = new Fl_Box(SCALE(5), 0, SCALE(390), SCALE(25), "Select DML to Toggle or Configure:");
      o->labelfont(1);
      o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      o->when(FL_WHEN_NEVER);
    } // Fl_Box* o
    { Fl_Return_Button* o = new Fl_Return_Button(SCALE(5), SCALE(440), SCALE(115), SCALE(25), "Configure");
      o->callback((Fl_Callback*)OnConfigure);
    } // Fl_Return_Button* o
    { Fl_Button* o = new Fl_Button(SCALE(520), SCALE(440), SCALE(115), SCALE(25), "Exit");
      o->callback((Fl_Callback*)OnExit);
    } // Fl_Button* o
    { pDMLList = new Fl_Browser(SCALE(5), SCALE(25), SCALE(630), SCALE(400));
      pDMLList->type(2);
      pDMLList->callback((Fl_Callback*)OnSelect);
      pDMLList->when(FL_WHEN_ENTER_KEY_ALWAYS);
    } // Fl_Browser* pDMLList
    { Fl_Button* o = new Fl_Button(SCALE(135), SCALE(440), SCALE(130), SCALE(25), "Enable/Disable");
      o->callback((Fl_Callback*)OnToggle);
    } // Fl_Button* o
    { pDMLSearch = new Fl_Input(SCALE(335), SCALE(440), SCALE(165), SCALE(25), "Search:");
      pDMLSearch->callback((Fl_Callback*)OnSearch);
      pDMLSearch->when(FL_WHEN_CHANGED);
    } // Fl_Input* pDMLSearch
    pMainWnd->set_modal();
    pMainWnd->end();
  } // Fl_Double_Window* pMainWnd
  return pMainWnd;
}
